#ifdef eHudColours
#undef eHudColours
#endif

enum eHudColoursNew {
    HUD_COLOUR_PURE_WHITE,
    HUD_COLOUR_WHITE,
    HUD_COLOUR_BLACK,
    HUD_COLOUR_GREY,
    HUD_COLOUR_GREYLIGHT,
    HUD_COLOUR_GREYDARK,
    HUD_COLOUR_RED,
    HUD_COLOUR_REDLIGHT,
    HUD_COLOUR_REDDARK,
    HUD_COLOUR_BLUE,
    HUD_COLOUR_BLUELIGHT,
    HUD_COLOUR_BLUEDARK,
    HUD_COLOUR_YELLOW,
    HUD_COLOUR_YELLOWLIGHT,
    HUD_COLOUR_YELLOWDARK,
    HUD_COLOUR_ORANGE,
    HUD_COLOUR_ORANGELIGHT,
    HUD_COLOUR_ORANGEDARK,
    HUD_COLOUR_GREEN,
    HUD_COLOUR_GREENLIGHT,
    HUD_COLOUR_GREENDARK,
    HUD_COLOUR_PURPLE,
    HUD_COLOUR_PURPLELIGHT,
    HUD_COLOUR_PURPLEDARK,
    HUD_COLOUR_PINK,
    HUD_COLOUR_RADAR_HEALTH,
    HUD_COLOUR_RADAR_ARMOUR,
    HUD_COLOUR_RADAR_DAMAGE,
	HUD_COLOUR_CLOCK,
	HUD_COLOUR_CASH,
	HUD_COLOUR_HEALTH,
	HUD_COLOUR_ARMOUR,
	HUD_COLOUR_BREATH,
	HUD_COLOUR_WEAPON_ICON,
	HUD_COLOUR_AMMO,
	HUD_COLOUR_WANTED_N,
	HUD_COLOUR_WANTED_A,
	HUD_COLOUR_ZONE_NAME,
	HUD_COLOUR_VEHICLE_NAME,
	HUD_COLOUR_RADIO_NAME_N,
	HUD_COLOUR_RADIO_NAME_A,
	HUD_COLOUR_HELP_TEXT,
	HUD_COLOUR_HELP_BOX,
	HUD_COLOUR_SUBTITLES,
	HUD_COLOUR_WASTED,
	HUD_COLOUR_BUSTED,
	HUD_COLOUR_MISSION_RESULT,
	HUD_COLOUR_MISSION_TITLE,
	HUD_COLOUR_DAMAGE,
};

class CHudColourNew {
public:
    char name[64];
    unsigned char r, g, b, a;
};

class CHudColoursNew {
public:
    CHudColourNew m_aColours[256];

public:
    void ReadColorsFromFile();
    CRGBA GetRGB(int color, unsigned char alpha);
    CRGBA GetRGB(const char* name, unsigned char alpha);
    CRGBA GetRGBA(const char* name);
    CRGBA GetRGBA(int color);
};

extern CHudColoursNew HudColourNew;